apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-use
  labels:
    app: rollout-nginx
    color: green

spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-nginx
      color: green
  template:
    metadata:
      labels:
        app: rollout-nginx
        color: green
    spec:
      containers:
        - name: rollout-nginx
          image: nginx:1.15.5
