apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-nginx
  labels:
    app: rollout-nginx
    canary: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-nginx
      canary: stable
  template:
    metadata:
      labels:
        app: rollout-nginx
        canary: stable
    spec:
      containers:
        - name: rollout-nginx
          image: nginx:1.15.5

---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  labels:
    app: rollout-nginx-svc
spec:
  type: LoadBalancer
  ports:
    - name: svc-nginx
      port: 80
      targetPort: 80
  selector:
    app: rollout-nginx
