apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-nginx
  labels:
    app: rollout-nginx
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-nginx
      color: blue
  template:
    metadata:
      labels:
        app: rollout-nginx
        color: blue
  spec:
    containers:
      - name: rollout-nginx
        image: nginx:1.12
