#namespace: kustomize-namespace

# namePrefix: 
nameSuffix: -green

commonLabels:
  app: rollout-nginx
  color: green


# 컨테이너 이미지로 특정 컨테이너 구분
images:
- name: nginx
  newTag: 1.16 # 새로운 태그 이름

resources:
- deployment.yaml
